compile: &defaults
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: /bin/bash -l -c "rake compile"
test:
  <<: *defaults
  command: /bin/bash -l -c "rake test"
bintest:
  <<: *defaults
  command: /bin/bash -l -c "rake test:bintest"
mtest:
  <<: *defaults
  command: /bin/bash -l -c "rake test:mtest"
bundle:
  <<: *defaults
  command: /bin/bash -l -c "bundle install"
clean:
  <<: *defaults
  command: /bin/bash -l -c "rake clean"
shell:
  <<: *defaults
  command: /bin/bash --login
all:
  <<: *defaults
  command: /bin/bash -l -c "rake all"
